// Foto d'epoca di Serracapriola. Sinistra: bianco e nero, destra: colorata.
// `year`: date stimate dall'aspetto delle foto ("circa"), da confermare. 1943 = ingresso degli Alleati.
export type MemoryPair = { left: string; right?: string; title: string; text: string; year?: string };

export const MEMORY_PAIRS: MemoryPair[] = [
  { left: "OZ3ieLjZI0pctNly5UXnH4UW", right: "NLTVwYgcjGZC2jol2x0ySIyM", title: "Operai con la scala", text: "Un gruppo di operai posa per la foto accanto a una lunga scala montata su un carro.", year: "1950" },
  { left: "bhLR2clgi0Td4Y9lDgkg81IH", right: "K4Hk0YkALLrizdYBY96ZjA6F", title: "Corso Garibaldi e la scala", text: "Un operaio lavora in cima a una scala sul lungo viale alberato.", year: "1950" },
  { left: "OFGGP1KBD9EqkDu1wLMcZa9Z", right: "XCuvOGdsgesqge01JrLb2Y8I", title: "Sulla spiaggia", text: "Barche e persone in abiti dell'epoca sulla spiaggia.", year: "1920" },
  { left: "QDeVAHMeOAikZHq3ajxxY0tN", right: "S2i56gfBJcjJoJX65QIni2Q0", title: "Piazza del Castello", text: "La piazza davanti al castello, con la gente che passeggia.", year: "1930" },
  { left: "PlhXUkDvm3OZHlzhGFFg1qrP", right: "bjyPwNCrdNu6exaLR764R6Yq", title: "Corso Garibaldi", text: "Corso Garibaldi ancora sterrato, con le case in fila e il palo della luce.", year: "1920" },
  { left: "P5oPOde6WSoPyv9QFXzQRJ05", right: "gCFuUgR4l1rSfuwv6A499JSe", title: "Corso Garibaldi pieno di gente", text: "Corso Garibaldi visto dall'alto, affollato di persone.", year: "1950" },
  { left: "Ry1u1XghiI1n2q5Elw1dF8za", right: "0OvanmMAvEB1ZzMPPATmAHBi", title: "La chiesetta nel prato", text: "La chiesetta isolata in mezzo al prato, fuori dal centro.", year: "1930" },
  { left: "i4S5Sg8l8m8oxTsB1eeANaub", right: "vwji0dfs24I4LcuzembQh1uf", title: "Corso Garibaldi alberato", text: "Il corso con le piante e, in fondo, la torre.", year: "1930" },
  { left: "Z47fXuCcjuh3N0MjiFb5uaho", right: "13oKAAcIOE4qUjeMT5H3e05X", title: "La piazza in festa", text: "Tanta gente riunita in piazza davanti ai palazzi.", year: "1950" },
  { left: "847Cr7WEZNITsUfY3PRBAiJe", right: "9HBaND5C2LSNXwyBbXk5IIHD", title: "Fiera Santa Rosalia", text: "Una folla davanti al castello, nel giorno della fiera di Santa Rosalia.", year: "1930" },
  { left: "P4BS4OVKit6gP5NudypSdrlO", right: "qXTpl3npVGtg76zeipPEn1L9", title: "L'arrivo degli americani", text: "Mezzi militari e soldati americani tra la gente nelle strade del paese.", year: "1943" },
  { left: "7uEbIjoA9uLmGXfavPOO12cz", right: "INycaU83I3dggHFr74oQ4dWU", title: "Soldati in strada", text: "Una strada del paese con mezzi e militari di passaggio.", year: "1943" },
  { left: "P7fZG1l5hLl9Bb0omLQGs8w5", right: "ISho2dNHdDXTlHlL86SJPLGw", title: "Il castello e le sue torri", text: "Il castello con la torre rotonda, tra alberi e passanti.", year: "1940" },
  { left: "5fIkReEpeAMVcijm0w3LuKh3", right: "air8qY6s7LChvCe0VJeKoyDv", title: "Il palazzo con il giardino", text: "Un antico palazzo circondato dal verde.", year: "1950" },
  { left: "i1yGTowtGfI52uzEYXuaVXMT", right: "GIvAVdz6P0nNO2TbDOCNJNfb", title: "Il mercato del bestiame", text: "Una grande folla con animali, forse giorno di fiera.", year: "1930" },
  { left: "KB12VQlr8Ypd3Ed0zhFaV1m5", right: "7SqWyg8gK3ibWizWo3ZEFihW", title: "Il corteo con le bandiere", text: "Un corteo di persone con le bandiere tricolori.", year: "1945" },
  { left: "9vC3RXqBYLmQBsRwJWg24OS0", right: "jaFuBeYUZQYXnQMv5j4YjRU8", title: "Il distributore Kendall", text: "Persone in posa davanti alle pompe di benzina Kendall.", year: "1935" },
  { left: "2yz1KbzYzw6gxRrrwfvfiylI", right: "LqzDTekr5VaxKD7evq4Gs579", title: "L'auto al distributore", text: "Un'auto d'epoca ferma accanto alle pompe di benzina.", year: "1935" },
  { left: "zojP2vkKigWEUUy5UkPEqio7", right: "vJ5dBMvJ4IhbUdME4OdnY0oA", title: "Corso Garibaldi e i lampioni", text: "Corso Garibaldi con i lampioni e le giovani piante.", year: "1930" },
  { left: "SK6hZi4uRWJ5AMhrEoUr261I", right: "CAosRtKxz5E05W9oss0BaPKH", title: "Il vicolo", text: "Un vicolo del centro storico con le case in pietra.", year: "1950" },
  { left: "mYSvGtDPGt63QvOfSHam0G0f", right: "s0zGubaBqSch4cs9PnHIyioz", title: "La biblioteca", text: "Una sala con scaffali pieni di libri antichi.", year: "1950" },
  { left: "TItZluwiKVbmjfWun2m52Gwf", right: "WAS3c7i301RmdWW3ThjV6zS7", title: "Il frantoio", text: "Operai al lavoro tra le macine e i macchinari.", year: "1940" },
  { left: "ujmqYNH1TNA0MlP0Xqctak2P", right: "qBzdhXkkP22tjhgZkYTXREOq", title: "Il castello dal giardino", text: "Il castello visto dal muretto, con le sue torri.", year: "1950" },
  { left: "aJWj485QVEbu9zhBdyJsix0h", right: "ws3hpZq5ZwnOryItD3hCdEmI", title: "La piazza del castello", text: "La piazza con il castello sullo sfondo e la gente a passeggio.", year: "1960" },
  { left: "k0xGFeoN7o4CCdEoVm3OimPq", right: "Ax6Uw1O1q371dZlew9Za7Xak", title: "La cerimonia con il carro armato", text: "Una folla attorno a un mezzo militare durante una cerimonia.", year: "1943" },
  { left: "21C2pMYOnY43J7D71b7tuAdP", right: "44mIPEjLI6r5Uxmj5eOw6Ce2", title: "Chiesa S. Anna", text: "Il fianco della chiesa di Sant'Anna.", year: "1970" },
  { left: "AJhFCi8Daa6BOHfKVbqCiA5S", right: "272dr34VWJ0BGH3l5I0hpWfp", title: "L'angolo della chiesa", text: "Un angolo di strada con la facciata della chiesa.", year: "1960" },
  { left: "fQ7bpDJwqwOoZ2Ac0R5DiJoK", right: "HZeBbjFSMD6QrIM2qIUFP8Ia", title: "La strada dall'alto", text: "Una strada del paese vista da una finestra alta.", year: "1930" },
  { left: "xKYFaD5t0MeG8vl9XfuDSliJ", right: "vhqyCZ1Ka6BN4HS4Ndvyc21I", title: "Il convento con i cipressi", text: "Il convento bianco con i cipressi e il muro di cinta.", year: "1930" },
  { left: "7L2RV2XzHAFWGWeNX1ADnnsz", right: "SrljXPmySfLF5eWTzaQNpayr", title: "Il castello e la strada", text: "Il castello e la strada che porta in piazza.", year: "1960" },
  { left: "QbAOcTpRGzVluxCNuhctiBwE", right: "x36HSwrN3yCjMbTUqJh1aryW", title: "Corso Garibaldi con il palo e la torre", text: "Il corso con il palo e la torre in fondo.", year: "1920" },
  { left: "PmrrLSl6rdeMU1C7RyTIloNa", right: "bGOjbdSENPEuzsu78iV6Lgue", title: "Il ponte danneggiato", text: "Un ponte rovinato con un fosso sotto.", year: "1943" },
  { left: "XJ4RWJzZI13ktNEMWiMXlMJb", right: "gdNDAIQPsv8609P1FkwD6CHj", title: "Lo stradone", text: "Un largo ancora sterrato con le case attorno.", year: "1930" },
  { left: "fKCRbixR3pU63cb3jlJqoYCv", right: "Zz7JWEFkWiwBRUZpbr00wK1U", title: "Il castello e la fontana", text: "Il castello e la fontana nell aiuola.", year: "1960" },
  { left: "US7tMPI2E2kS2msWLl48cgH7", right: "U54HxFKum6zKAZy2lRchPjNh", title: "La trebbiatura", text: "La macchina a vapore al lavoro nei campi.", year: "1930" },
  { left: "nky1HiHfa07LZofPsdMmEj4Z", right: "S5evyCHk2Gmm3u43ZNLv19vx", title: "La strada che sale", text: "La strada a curva che sale verso il paese.", year: "1950" },
  { left: "AhX28yqgBNkGZ0IZl70JFvWd", right: "iqHhzhBPDI74eUsOX5mPhKhQ", title: "Il ponte in costruzione", text: "Le grandi arcate del ponte con le impalcature.", year: "1930" },
  { left: "T6L6VVuyS72L8NxmNR7ezmha", right: "ICAMx3wNrgSFcmlLRI79127H", title: "Il Teatro Palazzo", text: "La facciata del vecchio Teatro Palazzo, con le colonne e il nome sopra l'ingresso.", year: "1935" },
  { left: "wz7kMG27b3vob7RMFRJizgsa", right: "4ZC3Hkye951deGo4D2u4b2Yg", title: "Il cantiere", text: "Un cantiere del paese, visto prima in bianco e nero e poi a colori.", year: "1950" },
];
